version: "2.2"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: devopsproj
      MYSQL_ROOT_PASSWORD: root
      
    restart: unless-stopped
    image: mysql
    
  backend:
    depends_on:
      - mysql-container3
    container_name: backend
    ports:
      - '8040:8040'
    image: fourat8/backend
    restart: unless-stopped
  frontend:
    depends_on:
      - backend
    # The name of the service
    container_name: frontend # Container name
    image: fourat8/frontend
    restart: always
    build: ./Angular
    ports:
      - '4200:4200' # Port mapping 
    volumes:
      - '.Angular:/home/serveur'
volumes:
  mysql-container3: { }
