version: "3"

services:
  mysql-container3:
    container_name: mysql-container3
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: devopsproj
      MYSQL_ROOT_PASSWORD: root
      
    restart: unless-stopped
    image: mysql
    
  backend:
    depends_on:
      - mysql-container3
    container_name: backend
    ports:
      - '8040:8040'
    image: fourat8/backend
    restart: unless-stopped
  frontend:
    depends_on:
      - backend
    # The name of the service
    container_name: frontend # Container name
    build: "crudtuto-Front"
    restart: unless-stopped
    ports:
      - '90:90' # Port mapping
    volumes:
      - '.:/app'
      - '/app/node_modules'
volumes:
  mysql-container3: { }
